//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.07 at 06:56:40 PM IST 
//


package com.phunware.jaxb.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="element" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="errortext" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="locatortype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="locatorvalue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "element"
})
@XmlRootElement(name = "OR")
public class OR {

    protected List<OR.Element> element;

    /**
     * Gets the value of the element property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the element property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OR.Element }
     * 
     * 
     */
    public List<OR.Element> getElement() {
        if (element == null) {
            element = new ArrayList<OR.Element>();
        }
        return this.element;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="errortext" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="locatortype" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="locatorvalue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Element {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String errortext;
        @XmlAttribute
        protected String exptext;
        @XmlAttribute
        protected String locatortype;
        @XmlAttribute
        protected String locatorvalue;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the errortext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrortext() {
            return errortext;
        }

        /**
         * Sets the value of the errortext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrortext(String value) {
            this.errortext = value;
        }
        
        /**
         * Gets the value of the exptext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExptext() {
            return exptext;
        }

        /**
         * Sets the value of the exptext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExptext(String value) {
            this.exptext = value;
        }

        /**
         * Gets the value of the locatortype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocatortype() {
            return locatortype;
        }

        /**
         * Sets the value of the locatortype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocatortype(String value) {
            this.locatortype = value;
        }

        /**
         * Gets the value of the locatorvalue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocatorvalue() {
            return locatorvalue;
        }

        /**
         * Sets the value of the locatorvalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocatorvalue(String value) {
            this.locatorvalue = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
